### ISSUE TITLE
パイプからの入力を受け取った後にキーボードからの入力を受け取れない

### ISSUE THREAD

**Issue by YO-RO** [YO-RO/scopus_tool#1]
```shell
cat input.csv | python3 -m spt.translate -m 4
/Users/user/Downloads/scopus_translation.csvを上書きしますか？ y/n
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/workspace/source_code/python_project/scopus_tool/src/spt/translate.py", line 111, in <module>
    main()
  File "/Users/user/workspace/source_code/python_project/scopus_tool/src/spt/translate.py", line 98, in main
    do_overwrite = ask_overwriting(output_file_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/workspace/source_code/python_project/scopus_tool/src/spt/translate.py", line 41, in ask_overwriting
    answer = input()
             ^^^^^^^
EOFError: EOF when reading a line
```

**Comment by YO-RO** [comment]
ttyに接続されていないのでパイプからの入力とキーボードからの入力の両方を受け取るのは無理。コマンド実行時にフラグをつけた場合にのみ上書きするようにする。
